# Generated by Django 2.1 on 2018-12-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USR_MSG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
