# Generated by Django 2.1 on 2018-12-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.NullBooleanField()),
                ('tel', models.CharField(max_length=15)),
                ('cat_b', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('birthday', models.DateField()),
                ('school', models.CharField(max_length=40)),
                ('real_score', models.PositiveSmallIntegerField()),
                ('pred_score', models.PositiveSmallIntegerField()),
                ('want_score', models.PositiveSmallIntegerField()),
                ('join_time', models.DateTimeField()),
                ('vip', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
